INSERT INTO course_category (id, name, created_at, updated_at)
VALUES
    (1, 'Java', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'Javascript', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'Ruby', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'C++', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 'Elixir', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
